Repository Ribbit-Network/ribbit-network-frog-hardware, pull requests merged in 2022-09, with the labels that each got.

#144 V3 BOM: Increased cable length to 200 mm #142
  hardware/v3/ribbit_network_frog_sensor_bom.csv
Labels: enhancement

#149 #148 Fixed broken debugging link
  hardware/v3/assembly-instructions/images/act_led.jpeg
  hardware/v3/assembly-instructions/images/adafruit_products_Mini_GPS_pinouts_LEDs.png
Labels: documentation

#151 Readme Edits for V3
  hardware/README.md
  hardware/v3/README.md
  hardware/v3/frog_sensor.drawio.svg
Labels: documentation, enhancement

#153 Moving Commits from the v3_instructions to the main
  hardware/v3/README.md
  hardware/v3/assembly-instructions/4-assembly.md
  hardware/v3/assembly-instructions/images/carrier and pi assembly.jpg
  hardware/v3/assembly-instructions/images/carrier and pi attached.jpg
  hardware/v3/assembly-instructions/images/carrier and pi overview.jpg
  hardware/v3/assembly-instructions/images/solder close up 1.jpg
  hardware/v3/assembly-instructions/images/solder close up 2.jpg
  hardware/v3/frog_sensor.drawio.svg
  hardware/v3/ribbit_network_frog_sensor_bom.csv
Labels: documentation, enhancement
